"""initial_create_users_table

Revision ID: 0964877d39ed
Revises: 
Create Date: 2026-02-14 02:31:56.353472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0964877d39ed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uid', sa.String(length=128), nullable=False, comment='Firebase UID'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='이메일'),
    sa.Column('name', sa.String(length=100), nullable=True, comment='이름'),
    sa.Column('picture', sa.String(length=500), nullable=True, comment='프로필 이미지 URL'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='활성 상태'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='수정일시'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
