"""add_url_to_news

Revision ID: 468cbf817139
Revises: 6521189d2125
Create Date: 2026-03-04 00:12:08.896404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '468cbf817139'
down_revision: Union[str, Sequence[str], None] = '6521189d2125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('url', sa.String(length=255), nullable=True, comment='뉴스 URL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'url')
    # ### end Alembic commands ###
