"""add_save_slots_table

Revision ID: 61373aea869c
Revises: 0964877d39ed
Create Date: 2026-02-18 01:33:05.339536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61373aea869c'
down_revision: Union[str, Sequence[str], None] = '0964877d39ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('save_slots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_uid', sa.String(length=128), nullable=False, comment='소유 유저 UID'),
    sa.Column('slot_number', sa.Integer(), nullable=False, comment='슬롯 번호 (1~3)'),
    sa.Column('game_state', sa.JSON(), nullable=False, comment='LogicManager의 전체 state JSON'),
    sa.Column('play_day', sa.Integer(), nullable=False, comment='진행 일차 (목록 표시용)'),
    sa.Column('dungeon_level', sa.Integer(), nullable=False, comment='던전 레벨 (목록 표시용)'),
    sa.Column('monster_count', sa.Integer(), nullable=False, comment='생존 몬스터 수 (목록 표시용)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='최초 저장일'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='마지막 저장일'),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_uid', 'slot_number', name='uq_user_slot')
    )
    op.create_index(op.f('ix_save_slots_user_uid'), 'save_slots', ['user_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_save_slots_user_uid'), table_name='save_slots')
    op.drop_table('save_slots')
    # ### end Alembic commands ###
