"""add_section_id_to_news

Revision ID: 6521189d2125
Revises: 77dba1e3b225
Create Date: 2026-03-02 19:32:30.896228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6521189d2125'
down_revision: Union[str, Sequence[str], None] = '77dba1e3b225'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('section_id', sa.Integer(), nullable=True, comment='섹션 ID'))
    op.create_index(op.f('ix_news_section_id'), 'news', ['section_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_section_id'), table_name='news')
    op.drop_column('news', 'section_id')
    # ### end Alembic commands ###
