"""add_news_table

Revision ID: 8fb692d90724
Revises: 61373aea869c
Create Date: 2026-03-02 18:58:11.553526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8fb692d90724'
down_revision: Union[str, Sequence[str], None] = '61373aea869c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('nid', sa.Integer(), nullable=False, comment='뉴스 ID'),
    sa.Column('title', sa.String(length=255), nullable=True, comment='제목'),
    sa.Column('summary', sa.String(length=1000), nullable=True, comment='요약'),
    sa.Column('question', sa.String(length=255), nullable=True, comment='질문'),
    sa.Column('option1', sa.String(length=255), nullable=True, comment='옵션 1'),
    sa.Column('option2', sa.String(length=255), nullable=True, comment='옵션 2'),
    sa.Column('option3', sa.String(length=255), nullable=True, comment='옵션 3'),
    sa.Column('option4', sa.String(length=255), nullable=True, comment='옵션 4'),
    sa.Column('answer_index', sa.Integer(), nullable=True, comment='정답'),
    sa.Column('explanation', sa.String(length=255), nullable=True, comment='설명'),
    sa.Column('when', sa.Integer(), nullable=True, comment='오전: 0, 오후: 1'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='수정일시'),
    sa.PrimaryKeyConstraint('nid')
    )
    op.create_index(op.f('ix_news_title'), 'news', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_title'), table_name='news')
    op.drop_table('news')
    # ### end Alembic commands ###
