"""add_url_to_news

Revision ID: e11dce88cd4f
Revises: 468cbf817139
Create Date: 2026-03-04 00:20:52.615249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e11dce88cd4f'
down_revision: Union[str, Sequence[str], None] = '468cbf817139'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('date', sa.String(length=255), nullable=True, comment='뉴스 날짜'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'date')
    # ### end Alembic commands ###
